### PR TITLE
Dash docset generate script and IOJS.docset dir

### PR DESCRIPTION
**Pull request by fundon**
https://github.com/iojs/io.js/issues/590

### CODE REVIEW

**Comment by fundon** [comment]
And I will add a task to iojs `Makefile`, named `dash`.
Have any  suggestion?

#### Usage:

```
$ iojs dash.js $(find out/doc/api/*.json)
$ cp -R  io.js/out/doc/api/* IOJS.docset/Contents/Resources/Documents/iojs.org/api
$ tar --exclude='.DS_Store' -cvzf IOJS.tgz IOJS.docset
```

**Comment by rvagg** [comment]
is the uppercasing necessary here? can it just be `iojs.tgz` and `iojs.docset`?

**Comment by fundon** [comment]
The icons come from iojs.org.
https://iojs.org/images/1.0.0.png

**Comment by chrisdickinson** [comment]
This seems to be for a [third party documentation tool](http://kapeli.com/dash) to consume and adds a dependency on sqlite3 for folks building docs. I'm curious: can this be moved downstream somehow? Could it be released as a separate package on npm for consuming the JSON output of the existing docs? Who is the target audience using Dash?

**Comment by fundon** [comment]
I pushed it to Dash-User-Contributions https://github.com/Kapeli/Dash-User-Contributions/pull/306.

**Pull request closed without merging**
